#!/usr/bin/env bash
# Run Lighthouse via Google's PageSpeed Insights API and write results to
# docs/lighthouse_results.md (paste-ready for README badges).
#
# Usage:
#   PSI_API_KEY=AIzaSy... ./scripts/run_lighthouse.sh
#
# Get a free key at https://developers.google.com/speed/docs/insights/v5/get-started.
# Without PSI_API_KEY the script still works (anonymous quota) but is rate-limited.
#
# Requires: curl, jq.

set -euo pipefail

ROUTES=(
  "/"
  "/validators"
  "/portfolio"
  "/simulate"
  "/methodology"
  "/stake"
)

BASE="${LIGHTHOUSE_BASE_URL:-https://stakesense-el77-git-main-california-mortgage-solutions.vercel.app}"
KEY_PARAM=""
if [ -n "${PSI_API_KEY:-}" ]; then
  KEY_PARAM="&key=${PSI_API_KEY}"
fi

OUT="docs/lighthouse_results.md"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

{
  echo "# Lighthouse / PageSpeed Insights"
  echo
  echo "Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "Base: ${BASE}"
  echo
  echo "| Route | Performance | Accessibility | Best Practices | SEO |"
  echo "|---|---|---|---|---|"
} > "$OUT"

for route in "${ROUTES[@]}"; do
  url_enc="$(printf %s "${BASE}${route}" | jq -sRr @uri)"
  for cat in performance accessibility best-practices seo; do
    out_file="$TMPDIR/$(echo "$route" | tr '/' '_')-$cat.json"
    curl -fsSL \
      "https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=${url_enc}&strategy=mobile&category=${cat}${KEY_PARAM}" \
      > "$out_file" || true
  done
  perf=$(jq -r '.lighthouseResult.categories.performance.score // empty' "$TMPDIR/$(echo "$route" | tr '/' '_')-performance.json" 2>/dev/null || echo "")
  a11y=$(jq -r '.lighthouseResult.categories.accessibility.score // empty' "$TMPDIR/$(echo "$route" | tr '/' '_')-accessibility.json" 2>/dev/null || echo "")
  bp=$(jq -r '.lighthouseResult.categories["best-practices"].score // empty' "$TMPDIR/$(echo "$route" | tr '/' '_')-best-practices.json" 2>/dev/null || echo "")
  seo=$(jq -r '.lighthouseResult.categories.seo.score // empty' "$TMPDIR/$(echo "$route" | tr '/' '_')-seo.json" 2>/dev/null || echo "")
  fmt() {
    if [ -z "$1" ] || [ "$1" = "null" ]; then echo "—"; else awk -v s="$1" 'BEGIN { printf "%d", s * 100 }'; fi
  }
  echo "| \`${route}\` | $(fmt "$perf") | $(fmt "$a11y") | $(fmt "$bp") | $(fmt "$seo") |" >> "$OUT"
done

echo "" >> "$OUT"
echo "_Mobile strategy. Generated by \`scripts/run_lighthouse.sh\`._" >> "$OUT"
echo "Wrote $OUT"
